apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp-deployment
  labels:
    app: nginxapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxapp
  template:
    metadata:
      labels:
        app: nginxapp
    spec:
      containers:
      - name: nginxserver
        image: aymenzarour/nginx-docker:latest
        ports:
        - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: nginxapp
spec:
  selector:
    app: nginxapp
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
spec:
  rules:
  - host: web.local.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginxapp
            port:
              number: 8080
